### ISSUE TITLE
[Feature Request] - Android Auto quality of life

### ISSUE THREAD

**Issue by kaibagley** [CappielloAntonio/tempo#128]
## Summary
1. Easier way to shuffle all
2. Easier way to play most recent song

## Description
1. This may not be the same for most people, but a lot of the time I prefer to shuffle all, which is super easy in the app: Just click "shuffle all" on the Discovery section. This is a bit more annoying in the AA UI: Activate AA > Tempo > Scroll Down > Starred Tracks > Play first song > check the shuffle button. Maybe there could be a shuffle icon on the Starred Tracks line in the main menu, or some other way.
2. I think it'd be very very nice to simply turn on AA, go to Tempo, and click one button to just play the most recent track. This is easy in the app too: Just click play. Maybe I'm missing a menu somewhere but I don't think this is possible in AA at the moment. Alternatively, I personally would be happy if Tempo autoplayed the most recent song (given it was my last-used media app) as soon as Android Auto is opened

## Use Case
Both are quality of life features, designed to remove multiple steps in a process I believe should be quick and easy.

**Comment by CappielloAntonio** [comment]
To try to fix the problem I implemented two new entries:
- The first shows all the songs listened to in order of playback (from newest to oldest)
- The second to show a selection of songs to be played randomly
As with the Shuffle All item on the home page, I don't really agree with its use, partly because I don't like things that are too random, partly because in this specific case it could increase the number of touches on the screen while driving.

In any case, if I decide to keep these two features they will be present in the next release of the app.

![image](https://github.com/CappielloAntonio/tempo/assets/14802539/15fdd6fb-c392-4bb3-b62d-815f5e781534)

![image](https://github.com/CappielloAntonio/tempo/assets/14802539/f1b2720c-3261-4915-bdd7-944ff6b75621)
