### ISSUE TITLE
[Feature Request] - show track title, album name, and artist name in top songs

### ISSUE THREAD

**Issue by Sohalt** [CappielloAntonio/tempo#204]
## Summary
Top Songs only show the album artwork. It would be good to also show song title, album name, and artist name.

## Description
I would like to have the song title, album name, and artist name shown on top of the album artwork in the 3x3 grid showing top songs for the last week.

## Use Case
Otherwise you cannot distinguish different song from the same album. You can't distinguish songs at all if you don't have album artwork.

## Additional context

![Screenshot_20240323-121830](https://github.com/CappielloAntonio/tempo/assets/2157287/7a62db11-8844-4630-9861-d9309404b95a)

**Comment by CappielloAntonio** [comment]
Hi @Sohalt, I thought I'd remove the grid of top songs listened to after the many complaints received, to replace it with the more classic paged list. This allows you to have a better detailed view and access to the bottomSheetDialog for advanced functions. In addition, the LAST WEEK label has become clickable, in order to vary the period taken into consideration, which will be LAST WEEK, LAST MONTH and LAST YEAR for the moment but which I will probably change.

![Screenshot_20240526-212453_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/19c8bc9c-18a9-4280-9b2d-f6a5e7944441)
