### ISSUE TITLE
Suggested Workflow

### ISSUE THREAD

**Issue by c0utta** [CappielloAntonio/tempo#22]
Hi Antonio,

You already know me and have access to my server ;)

I would like to understand how to use Tempo to suit my workflow.

I want to shuffle starred items (artist, album and track).  If I turn on "Sync starred tracks.." how do I use Tempo to play them?

Thanks,

c0utta

**Comment by CappielloAntonio** [comment]
Hi @c0utta, nice to hear from you. 
I don't think I understood the question correctly. At this time, you can shuffle your favorite songs by going to (Music) Home, Starred Tracks, See All, and then shuffle songs.

The "Sync starred tracks for offline use" option is for downloading your favorite songs so you always have them at hand.

By enabling the option you'll download all the tracks in your favorites and when a new track is added to your favorites it will be the downloaded as well.

Please note that you do not need to enable this option to shuffle your favorite songs and that, due to restrictions imposed by the Subsonic API, I can easily work with favorite tracks and not with favorite albums and artists (which would require several successive API calls).

**Comment by c0utta** [comment]
On my home screen, I don't see "Starred Tracks, See All, and then shuffle songs.".

I have:
- Discovery
- Best of
- Radio stations
- Your top songs
- Starred artists
- Flashback

Feel free to connect to my server and I assume you'll see what I see.

I would like to shuffle all my starred items (artist, album & track), not just tracks.

**Comment by CappielloAntonio** [comment]
Do you see the new section appearing on the home screen if you add a new track to your favorites by pressing the heart icon in the music player or by long pressing on a song and then pressing the heart?

Using the user specially created by you, I put respectively a track, an album and an artist among the favourites, and I see them appearing in the home page.

As I mentioned before, shuffle only works on favorite tracks.

![Screenshot_20230730-152000_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/60f5a90a-fe7f-4611-a198-7d00656554c5)

**Comment by c0utta** [comment]
Yes, now that I have starred the same track within Tempo (Obscenery by QOTSA) my Home screen has changed dramatically:

- Discovery
- Made for you
- Best of
- Radio stations
- Your top songs
- Starred tracks
- Starred albums
- Starred artists
- New releases
- Flashback
- Most played
- Last played
- Recently added

Many more options that weren't there before.

I understand that I cannot play all starred items - probably more of a feature request.

I have an automatically generated playlist of my starred items, but it causes Tempo to crash - I assume too many items (6505 tracks).  I'll raise this as an issue when you're ready ;)

**Comment by CappielloAntonio** [comment]
No need to create a new issue. Just tell me if it's better now with this apk.

The app has a different signature, so you don't have to uninstall your current version.

As for the new sections that have appeared, yes, everything is as expected. The new sections rely on the presence of favourites. Since these were not there, it was impossible to create new sections.

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/12209351/app-notquitemy-debug.zip)

**Comment by c0utta** [comment]
Yes, the playlist now loads.  Pressing "Play" or "Shuffle" doesn't play anything though.

**Comment by CappielloAntonio** [comment]
Does it not play anything or is it just slow? (very slow)

**Comment by CappielloAntonio** [comment]
Anyway, could you please test this new apk?

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/12209442/app-notquitemy-debug.zip)

**Comment by c0utta** [comment]
[Does it not play anything or is it just slow? (very slow)] - Did not play anything after 15 minutes.

Latest APK found 23 more tracks (!) but still loading after 15 minutes.

**Comment by CappielloAntonio** [comment]
I'm sorry, I think I didn't quite understand the problem. 
In order to reproduce the problem, could you make this playlist with thousands of tracks accessible by my user as well on your server?

**Comment by c0utta** [comment]
I have made the "c0utta" playlist public for you to test. 

It is a playlist that contains all my starred items.

**Comment by CappielloAntonio** [comment]
I tried to play this playlist and this is the result. 
Loading content in general is very slow, so not just that playlist, but once you load the list it is smooth and the function keys work.

https://github.com/CappielloAntonio/tempo/assets/14802539/3f730a2a-42d5-4d87-b4dc-dfd42a6dfd73

(Slowness issue is not a problem now, it can be caused by many factors, like connection, distance, server, etc).

This is the apk I used:
[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/12212597/app-notquitemy-debug.zip)

**Comment by c0utta** [comment]
OK, that's now working for me - playlist loads after about 15 seconds.  That's fine for me, and it will only get faster.

I'm downloading the entire playlist and will then test for a few days.

What are your plans for keeping playlists synced?
