### ISSUE TITLE
Will it support EMBY? 

### ISSUE THREAD

**Issue by Yumipk** [CappielloAntonio/tempo#248]
There's also quite a lot of emby music

(>﹏<)

**Comment by jonas-resch** [comment]
I think this would be a lot of work since this App is built to interface with a Subsonic compatible Server.
Therefore, in my opinion it would be best if someone creates an Emby Plugin to support the Subsonic API. According to [this](https://emby.media/community/index.php?/topic/123087-any-interest-in-getting-a-stable-subsonic-extension-to-embys-api/) forum post someone is developing it, but I don't know if and when it will be finished.

**Comment by CappielloAntonio** [comment]
Not now, but who knows in the future. After all, few know it, but Tempo was born as a music player for Jellyfin
