### ISSUE TITLE
[Feature Request] Add an "Auto" option for replay gain

### ISSUE THREAD

**Issue by picklepopper1** [CappielloAntonio/tempo#57]
There are apps that I've used that have this feature. Basically, it checkes the queue to see if the next song is from the same album, and if it is: use "album replay gain", if not: use "track replay gain,". 

Alternatively, it could check if an album is playing, and if not, to default to "track". 

It's not foollroof, but it's works reasonably well.

**Comment by picklepopper1** [comment]
No, this doesn't resolve the issue. None of my tracks have missing replay
gain tags for track, or album tags. Choosing the second option would always
give me album replay gain, even if I was in a playlist, because album
replay gain tags would never be missing.

The system I am proposing would assume both tags exist and intelligently
choose which one to apply based on playback context.

The desired approach for an in app description would be as follows:

Replay Gain in the app automatically adjusts audio volume levels to provide
a consistent listening experience. You can choose between "Track preferred"
for individual tracks, "Album preferred" for entire albums, or "Auto" which
selects "Track" for playlists and "Album" for albums based on the context.

I have seen devs use two approaches:

* Pick the the replay gain tag based on what the user selected: album gain
if album is selected, track gain else.

* A simpler method that checks if the next track is from the same album.
I'd yes, album gain, else, track gain.

**Comment by CappielloAntonio** [comment]
Let's see if this approach makes sense.
- Let's remove the wording "Preferred", or it is Replay Gain of the track type or of the album type. If I choose track and this is absent, then the gain is reset.

- Let's add Auto. If it is of type Auto and the track being played belongs to the same album as the previous one then I try to set the Replay Gain of the album, otherwise I go into fallback with that of the track.

- If the Replay Gain is disabled or the track does not contain metadata, then the replay gain is reset.

If further edge cases come to mind, we discuss them.

**Comment by picklepopper1** [comment]
This is a great approach. I believe the examples you've given cover all cases I'm familiar with.

Thanks for being so receptive. This was an excellent interaction.

**Comment by CappielloAntonio** [comment]
I just committed these changes https://github.com/CappielloAntonio/tempo/commit/dee60e5e8f602734a9872ca40d0a54b707129757, I should publish a new version of the app soon ready to be tested. If you encounter any problems, please reopen this issue.
