### ISSUE TITLE
Back button behavior in "Download" section is unintuitive

### ISSUE THREAD

**Issue by GallowsDove** [CappielloAntonio/tempo#60]
When you're in a "Download" section and use the back button (The hardware one, or gestures on newer androids), it should take you back one step within the "Download" tab, instead of taking you straight to the previous tab.

### Example:
You go to "Download" tab, and select filter by artist, then click on an artist. This shows the albums.

##### Expected behavior
When you hit back button in this situation, it should take you back to the artist view within the "Download" tab

#### Actual behavior:
It takes you to the previous tab

**Comment by CappielloAntonio** [comment]
Hi @GallowsDove, I just pushed a fix for this. It seems to work and I think I'll leave it that way if no problems arise. 

The reason why before there wasn't a stack navigation respecting the system one is because there was only one fragment, the various views were filters of the track list. Solving the problem wasn't trivial because I had to emulate the normal stack, and it took a lot longer than expected.

Anyway, I'm closing this issue, if there are any other issues feel free to reopen it.
