### ISSUE TITLE
[Feature Request] Share

### ISSUE THREAD

**Issue by cottinghamk** [CappielloAntonio/tempo#67]
Navidrome (and I assume other servers that follow the Subsonic spec) supports sharing artist, album, song and playlist links. See https://www.navidrome.org/docs/usage/sharing/

Would it be possible for Tempo to support such functionality?

**Comment by CappielloAntonio** [comment]
Hi @cottinghamk, I have added the ability to share songs, albums and playlists. It is not possible to share the artists however. I have just released a new version of the app, the functionality needs to be further tested, but the basis is now there. Sharing must be enabled in the settings because not all servers allow sharing files.

**Comment by cottinghamk** [comment]
Looks like it's working so far @CappielloAntonio. I'll test and report back if I see anything abnormal. Thanks!

**Comment by CappielloAntonio** [comment]
At the moment it wouldn't be possible without distorting part of the app. I don't rule out working on this integration in the future, but at the moment it's not possible to open shared links with the app.
