### ISSUE TITLE
[BUG] - Can't download subfolders (or wrong three dots icon)

### ISSUE THREAD

**Issue by TH0MVS** [CappielloAntonio/tempo#91]
## Describe the bug
 In Music Library, the three dots icon appear when you enter any folder, regarless if its a folder with files (tracks) or folders (albums). My music is organized by artists, with subfolders per albums. If you can enter a folder with files, you can download them. If its a subfolder, nothing happen.

## Expected behavior
You should be able to download subfolders if it's possible, or the three dots icon should appear only where you can download.

## To Reproduce
1. Open the app (duh!)
2. Go to Library at the bottom
3. Enter Music Library at the top
4. Enter in any folder with subfolder
5. Three dots icon appear at the top right
6. Click Download all: nothing happen

## Environment
 - Android device: Pixel 6 (GrapheneOS), Redmi Note 10 Pro (ArrowOS)
 - Android OS version: 13 on both
 - App version: 3.5.7 on both
 - Other relevant details: Navidrome 0.49.3

## Logs or Screenshots
N/A, can make some if useful

## Additional context
Best subsonic app on earth, love it !

**Comment by CappielloAntonio** [comment]
Yes, @TH0MVS, you're right. The context menu relating to download within subfolders should only appear if there are files in the folder that can be downloaded (and this should be made more explicit). Unfortunately I cannot recursively download all the files starting from the current folder because I would have to make various subsequent calls to the server, for each level and for each folder, not knowing when to stop. For this reason I chose the path of immediate folder download.

**Comment by CappielloAntonio** [comment]
Okay, now the download button will be visible only if there are files to download in the current folder. Additionally, a dialog will be displayed warning the user that the download will not be recursive. I leave a test apk here in case someone wants to test the function, and I close this issue. If there are problems, you can reopen it.

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/12874308/app-tempo-debug.zip)
